# Generated by Django 4.1.2 on 2022-11-14 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroSerie', models.CharField(max_length=30)),
                ('Localidad', models.TextField(max_length=25)),
                ('Lote', models.CharField(max_length=30)),
                ('Fecha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='entregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.TextField(max_length=25)),
                ('Serie', models.CharField(max_length=10)),
                ('Cliente', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zona', models.CharField(max_length=50)),
                ('CodigoPostal', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.TextField(max_length=25)),
                ('Nombre', models.TextField(max_length=25)),
                ('Color', models.TextField(max_length=25)),
                ('Año', models.CharField(max_length=10)),
                ('Disponible', models.TextField(max_length=10)),
                ('Ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='vehiculos.vehiculos')),
            ],
        ),
    ]
