# Generated by Django 4.1.2 on 2022-11-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
