# Generated by Django 4.1.3 on 2022-11-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_almacen_fecha_alter_entregas_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='Localidad',
        ),
        migrations.AddField(
            model_name='almacen',
            name='Modelo',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='Lote',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='NumeroSerie',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='Cliente',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='Año',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
