# Generated by Django 4.1.3 on 2022-11-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_almacen_numalmacen_entregas_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregas',
            name='LugarEntrega',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
