# Generated by Django 4.1.3 on 2022-12-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_entregas_lugarentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='Hora',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='Lugar',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='Color',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='Disponible',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='Marca',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
    ]
